// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for educational content
  tutorialSidebar: [
    'intro',
    'module-1/chapter-1',  // New UI components demo
    {
      type: 'category',
      label: 'Module 1: Introduction to Physical Books',
      items: [
        'modules/module-1/chapter-1',
        'modules/module-1/chapter-2',
        'modules/module-1/chapter-3',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Advanced Physical Book Concepts',
      items: [
        'modules/module-2/chapter-1',
        'modules/module-2/chapter-2',
        'modules/module-2/chapter-3',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'modules/module-3/chapter-1',
        'modules/module-3/chapter-2',
        'modules/module-3/chapter-3',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'modules/module-4/chapter-1',
        'modules/module-4/chapter-2',
        'modules/module-4/chapter-3',
      ],
    },
  ],
};

module.exports = sidebars;